In [1]:
import requests
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
import time
import os
import glob
import numpy as np 
import ast

In [ ]:
url = "https://clinicaltrials.gov/api/v2/studies"

params = {
    "countTotal": "true",
    "filter.overallStatus": "NOT_YET_RECRUITING|RECRUITING",
    #"postFilter.advanced": "AREA[StartDate]2024",
    "pageSize": 1000,
}

page = 1
session = requests.Session()

# cria pasta de saída
os.makedirs("clinicaltrials_pages", exist_ok=True)

while True:

    try:
        response = session.get(url, params=params, timeout=60)
        response.raise_for_status()
    except requests.exceptions.RequestException as e:
        print(f"Erro na requisição: {e}")
        print("Tentando novamente em 10s...")
        time.sleep(10)
        continue

    data = response.json()
    studies = data.get("studies", [])

    if not studies:
        break

    df = pd.json_normalize(studies)

    file_path = f"clinicaltrials_pages/page_{page}.parquet"
    df.to_parquet(file_path, index=False)

    print(f"Página {page} salva")

    next_page = data.get("nextPageToken")

    if not next_page:
        break

    params["pageToken"] = next_page
    page += 1


print("Extração finalizada")

Página 1 salva
Página 2 salva
Página 3 salva
Página 4 salva
Página 5 salva
Página 6 salva
Página 7 salva
Página 8 salva
Página 9 salva
Página 10 salva
Página 11 salva
Página 12 salva
Página 13 salva
Página 14 salva
Página 15 salva
Página 16 salva
Página 17 salva
Página 18 salva
Página 19 salva
Página 20 salva
Página 21 salva
Página 22 salva
Página 23 salva
Página 24 salva
Página 25 salva
Página 26 salva
Página 27 salva
Página 28 salva
Página 29 salva
Página 30 salva
Página 31 salva
Página 32 salva
Página 33 salva
Página 34 salva
Página 35 salva
Página 36 salva
Página 37 salva
Página 38 salva
Página 39 salva
Página 40 salva
Página 41 salva
Página 42 salva
Página 43 salva
Página 44 salva
Página 45 salva
Página 46 salva
Página 47 salva
Página 48 salva
Página 49 salva
Página 50 salva
Página 51 salva
Página 52 salva
Página 53 salva
Página 54 salva
Página 55 salva
Página 56 salva
Página 57 salva
Página 58 salva
Página 59 salva
Página 60 salva
Página 61 salva
Página 62 salva
Página 63 salva
Página 64 salva
Página 65 salva
Página 66 salva
Página 67 salva
Página 68 salva
Página 69 salva
Página 70 salva
Página 71 salva
Página 72 salva
Página 73 salva
Página 74 salva
Página 75 salva
Página 76 salva
Página 77 salva
Página 78 salva
Página 79 salva
Página 80 salva
Página 81 salva
Página 82 salva
Página 83 salva
Página 84 salva
Página 85 salva
Página 86 salva
Página 87 salva
Página 88 salva
Página 89 salva
Página 90 salva
Página 91 salva
Página 92 salva
Página 93 salva
Página 94 salva
Extração finalizada

In [3]:
files = glob.glob("clinicaltrials_pages/*.parquet")

df_final = pd.concat(
    [pd.read_parquet(f) for f in files],
    ignore_index=True
)

In [4]:
list(df_final.columns)

['hasResults',
 'protocolSection.identificationModule.nctId',
 'protocolSection.identificationModule.orgStudyIdInfo.id',
 'protocolSection.identificationModule.organization.fullName',
 'protocolSection.identificationModule.organization.class',
 'protocolSection.identificationModule.briefTitle',
 'protocolSection.identificationModule.officialTitle',
 'protocolSection.statusModule.statusVerifiedDate',
 'protocolSection.statusModule.overallStatus',
 'protocolSection.statusModule.expandedAccessInfo.hasExpandedAccess',
 'protocolSection.statusModule.startDateStruct.date',
 'protocolSection.statusModule.startDateStruct.type',
 'protocolSection.statusModule.primaryCompletionDateStruct.date',
 'protocolSection.statusModule.primaryCompletionDateStruct.type',
 'protocolSection.statusModule.completionDateStruct.date',
 'protocolSection.statusModule.completionDateStruct.type',
 'protocolSection.statusModule.studyFirstSubmitDate',
 'protocolSection.statusModule.studyFirstSubmitQcDate',
 'protocolSection.statusModule.studyFirstPostDateStruct.date',
 'protocolSection.statusModule.studyFirstPostDateStruct.type',
 'protocolSection.statusModule.lastUpdateSubmitDate',
 'protocolSection.statusModule.lastUpdatePostDateStruct.date',
 'protocolSection.statusModule.lastUpdatePostDateStruct.type',
 'protocolSection.sponsorCollaboratorsModule.responsibleParty.type',
 'protocolSection.sponsorCollaboratorsModule.leadSponsor.name',
 'protocolSection.sponsorCollaboratorsModule.leadSponsor.class',
 'protocolSection.oversightModule.oversightHasDmc',
 'protocolSection.oversightModule.isFdaRegulatedDrug',
 'protocolSection.oversightModule.isFdaRegulatedDevice',
 'protocolSection.descriptionModule.briefSummary',
 'protocolSection.descriptionModule.detailedDescription',
 'protocolSection.conditionsModule.conditions',
 'protocolSection.conditionsModule.keywords',
 'protocolSection.designModule.studyType',
 'protocolSection.designModule.patientRegistry',
 'protocolSection.designModule.designInfo.observationalModel',
 'protocolSection.designModule.designInfo.timePerspective',
 'protocolSection.designModule.enrollmentInfo.count',
 'protocolSection.designModule.enrollmentInfo.type',
 'protocolSection.armsInterventionsModule.armGroups',
 'protocolSection.outcomesModule.primaryOutcomes',
 'protocolSection.outcomesModule.secondaryOutcomes',
 'protocolSection.eligibilityModule.eligibilityCriteria',
 'protocolSection.eligibilityModule.healthyVolunteers',
 'protocolSection.eligibilityModule.sex',
 'protocolSection.eligibilityModule.genderBased',
 'protocolSection.eligibilityModule.minimumAge',
 'protocolSection.eligibilityModule.maximumAge',
 'protocolSection.eligibilityModule.stdAges',
 'protocolSection.eligibilityModule.studyPopulation',
 'protocolSection.eligibilityModule.samplingMethod',
 'protocolSection.contactsLocationsModule.centralContacts',
 'protocolSection.contactsLocationsModule.locations',
 'protocolSection.ipdSharingStatementModule.ipdSharing',
 'protocolSection.ipdSharingStatementModule.description',
 'protocolSection.ipdSharingStatementModule.url',
 'derivedSection.miscInfoModule.versionHolder',
 'derivedSection.miscInfoModule.removedCountries',
 'derivedSection.conditionBrowseModule.meshes',
 'derivedSection.conditionBrowseModule.ancestors',
 'protocolSection.identificationModule.secondaryIdInfos',
 'protocolSection.sponsorCollaboratorsModule.collaborators',
 'protocolSection.designModule.phases',
 'protocolSection.designModule.designInfo.allocation',
 'protocolSection.designModule.designInfo.interventionModel',
 'protocolSection.designModule.designInfo.interventionModelDescription',
 'protocolSection.designModule.designInfo.primaryPurpose',
 'protocolSection.designModule.designInfo.maskingInfo.masking',
 'protocolSection.armsInterventionsModule.interventions',
 'protocolSection.outcomesModule.otherOutcomes',
 'protocolSection.contactsLocationsModule.overallOfficials',
 'protocolSection.ipdSharingStatementModule.infoTypes',
 'protocolSection.ipdSharingStatementModule.timeFrame',
 'protocolSection.sponsorCollaboratorsModule.responsibleParty.investigatorFullName',
 'protocolSection.sponsorCollaboratorsModule.responsibleParty.investigatorTitle',
 'protocolSection.sponsorCollaboratorsModule.responsibleParty.investigatorAffiliation',
 'protocolSection.oversightModule.isUsExport',
 'derivedSection.interventionBrowseModule.meshes',
 'protocolSection.identificationModule.acronym',
 'protocolSection.referencesModule.references',
 'protocolSection.referencesModule.seeAlsoLinks',
 'derivedSection.interventionBrowseModule.ancestors',
 'protocolSection.designModule.designInfo.maskingInfo.whoMasked',
 'protocolSection.designModule.bioSpec.retention',
 'protocolSection.designModule.bioSpec.description',
 'protocolSection.ipdSharingStatementModule.accessCriteria',
 'protocolSection.eligibilityModule.genderDescription',
 'protocolSection.designModule.designInfo.maskingInfo.maskingDescription',
 'documentSection.largeDocumentModule.largeDocs',
 'protocolSection.designModule.targetDuration',
 'protocolSection.referencesModule.availIpds',
 'protocolSection.identificationModule.orgStudyIdInfo.type',
 'protocolSection.identificationModule.orgStudyIdInfo.link',
 'protocolSection.oversightModule.isUnapprovedDevice',
 'annotationSection.annotationModule.unpostedAnnotation.unpostedResponsibleParty',
 'annotationSection.annotationModule.unpostedAnnotation.unpostedEvents',
 'derivedSection.miscInfoModule.submissionTracking.estimatedResultsFirstSubmitDate',
 'derivedSection.miscInfoModule.submissionTracking.submissionInfos',
 'protocolSection.identificationModule.nctIdAliases',
 'documentSection.largeDocumentModule.noSap',
 'protocolSection.statusModule.expandedAccessInfo.nctId',
 'protocolSection.statusModule.expandedAccessInfo.statusForNctId',
 'protocolSection.oversightModule.isPpsd',
 'protocolSection.statusModule.dispFirstSubmitDate',
 'protocolSection.statusModule.dispFirstPostDateStruct.date',
 'protocolSection.statusModule.dispFirstPostDateStruct.type',
 'protocolSection.sponsorCollaboratorsModule.responsibleParty.oldNameTitle',
 'protocolSection.sponsorCollaboratorsModule.responsibleParty.oldOrganization',
 'protocolSection.statusModule.resultsFirstSubmitDate',
 'protocolSection.statusModule.resultsFirstSubmitQcDate',
 'protocolSection.statusModule.resultsFirstPostDateStruct.date',
 'protocolSection.statusModule.resultsFirstPostDateStruct.type',
 'resultsSection.participantFlowModule.preAssignmentDetails',
 'resultsSection.participantFlowModule.groups',
 'resultsSection.participantFlowModule.periods',
 'resultsSection.baselineCharacteristicsModule.populationDescription',
 'resultsSection.baselineCharacteristicsModule.groups',
 'resultsSection.baselineCharacteristicsModule.denoms',
 'resultsSection.baselineCharacteristicsModule.measures',
 'resultsSection.outcomeMeasuresModule.outcomeMeasures',
 'resultsSection.adverseEventsModule.frequencyThreshold',
 'resultsSection.adverseEventsModule.timeFrame',
 'resultsSection.adverseEventsModule.description',
 'resultsSection.adverseEventsModule.eventGroups',
 'resultsSection.adverseEventsModule.seriousEvents',
 'resultsSection.adverseEventsModule.otherEvents',
 'resultsSection.moreInfoModule.certainAgreement.piSponsorEmployee',
 'resultsSection.moreInfoModule.certainAgreement.restrictionType',
 'resultsSection.moreInfoModule.certainAgreement.restrictiveAgreement',
 'resultsSection.moreInfoModule.certainAgreement.otherDetails',
 'resultsSection.moreInfoModule.pointOfContact.title',
 'resultsSection.moreInfoModule.pointOfContact.organization',
 'resultsSection.moreInfoModule.pointOfContact.email',
 'resultsSection.moreInfoModule.pointOfContact.phone',
 'derivedSection.miscInfoModule.submissionTracking.firstMcpInfo.postDateStruct.date',
 'derivedSection.miscInfoModule.submissionTracking.firstMcpInfo.postDateStruct.type',
 'protocolSection.statusModule.dispFirstSubmitQcDate',
 'resultsSection.participantFlowModule.recruitmentDetails']

In [5]:
df_final

,hasResults,protocolSection.identificationModule.nctId,protocolSection.identificationModule.orgStudyIdInfo.id,protocolSection.identificationModule.organization.fullName,protocolSection.identificationModule.organization.class,protocolSection.identificationModule.briefTitle,protocolSection.identificationModule.officialTitle,protocolSection.statusModule.statusVerifiedDate,protocolSection.statusModule.overallStatus,protocolSection.statusModule.expandedAccessInfo.hasExpandedAccess,...,resultsSection.moreInfoModule.certainAgreement.restrictiveAgreement,resultsSection.moreInfoModule.certainAgreement.otherDetails,resultsSection.moreInfoModule.pointOfContact.title,resultsSection.moreInfoModule.pointOfContact.organization,resultsSection.moreInfoModule.pointOfContact.email,resultsSection.moreInfoModule.pointOfContact.phone,derivedSection.miscInfoModule.submissionTracking.firstMcpInfo.postDateStruct.date,derivedSection.miscInfoModule.submissionTracking.firstMcpInfo.postDateStruct.type,protocolSection.statusModule.dispFirstSubmitQcDate,resultsSection.participantFlowModule.recruitmentDetails
0,False,NCT05659901,NH00005,"Ionis Pharmaceuticals, Inc.",INDUSTRY,Rocket Study: A Study to Characterize Biomarke...,Integrated Prospective and Retrospective Obser...,2026-03,RECRUITING,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,False,NCT05380401,HSC20220120H,The University of Texas Health Science Center ...,OTHER,Metabolic Mechanisms Induced by Enteral DHA an...,Metabolic Mechanisms Induced by Enteral Docosa...,2025-09,RECRUITING,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,False,NCT05698901,22CT026be,Mackay Memorial Hospital,OTHER,Biomarkers and Cardiac Imaging Diagnostic Assa...,Biomarkers and Cardiac Imaging Diagnostic Assa...,2023-11,RECRUITING,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,False,NCT00794001,GOE-01-10-07,St.Bernward Hospital,OTHER,Feedback Intervention and Treatment Times in S...,Feedback Intervention and Treatment Times in S...,2023-03,RECRUITING,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,False,NCT05754281,STUDY00000130,Joslin Diabetes Center,OTHER,The PRECISION II Study: Evaluating the Accurac...,The PRECISION II Study: Evaluating the Accurac...,2025-08,RECRUITING,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93232,False,NCT07452120,DIPB vs. SIFIB,Sivas Numune Hospital,OTHER_GOV,DIPB vs. SIFIB for Postoperative Analgesia Aft...,Comparison of the Effects of Deep Iliacus Plan...,2026-02,NOT_YET_RECRUITING,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93233,False,NCT07389720,95/24 (ex 1105),IRCCS Eugenio Medea,OTHER,Characterization of (A)Typical Sensorimotor Pa...,Characterization of (A)Typical Sensorimotor Pa...,2026-02,RECRUITING,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93234,False,NCT05779124,sBA-KTX-2023,"First Affiliated Hospital, Sun Yat-Sen University",OTHER,BAFF/APRIL in Kidney Transplant Rejection Risk...,Soluble B-Cell Activating Factor and a Prolife...,2023-03,NOT_YET_RECRUITING,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93235,False,NCT07348523,OMUKAEK 2025/247,Samsun University,OTHER,Comparison of the Postoperative Analgesic Effi...,Comparison of the Effectiveness of Classical a...,2025-12,RECRUITING,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93236,False,NCT07473323,MTX-439-K101,Mediar Therapeutics,INDUSTRY,Evaluation of MTX-439 in Healthy Adults and Ad...,"A Phase 1 Randomized, Double-blind, Dose-Escal...",2026-03,NOT_YET_RECRUITING,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
map_columns = {
    'protocolSection.identificationModule.nctId': 'NCT Number',
    'protocolSection.identificationModule.officialTitle': 'Study Title',
    'protocolSection.statusModule.startDateStruct.date': 'Start Date',
    'protocolSection.statusModule.studyFirstPostDateStruct.date': 'First Posted',
    'protocolSection.statusModule.primaryCompletionDateStruct.date': 'Completion Date',
    'protocolSection.sponsorCollaboratorsModule.leadSponsor.name': 'Sponsor',
    'protocolSection.sponsorCollaboratorsModule.leadSponsor.class': 'Funder Type',
    'protocolSection.conditionsModule.conditions': 'Conditions',
    'protocolSection.designModule.studyType': 'Study Type',
    'protocolSection.designModule.phases': 'Phases',
    'protocolSection.designModule.enrollmentInfo.count': 'Enrollment',
    'protocolSection.armsInterventionsModule.interventions': 'Intervention/Intervention Type',
    'protocolSection.contactsLocationsModule.locations': 'Country',
    'protocolSection.sponsorCollaboratorsModule.collaborators': 'Collaborators',
    'protocolSection.statusModule.overallStatus': 'Study Status'
}

df_final = df_final.rename(columns=map_columns)

df_final = df_final[['NCT Number', 'Study Title', 'Start Date', 'First Posted', 'Completion Date','Sponsor', 'Funder Type', 'Conditions','Study Type','Phases','Enrollment','Intervention/Intervention Type','Country','Collaborators', 'Study Status']]

In [7]:
df_final

,NCT Number,Study Title,Start Date,First Posted,Completion Date,Sponsor,Funder Type,Conditions,Study Type,Phases,Enrollment,Intervention/Intervention Type,Country,Collaborators,Study Status
0,NCT05659901,Integrated Prospective and Retrospective Obser...,2022-10-03,2022-12-21,2029-03,"Ionis Pharmaceuticals, Inc.",INDUSTRY,[Pelizaeus-Merzbacher Disease],OBSERVATIONAL,None,32.0,None,"[{'city': 'Atlanta', 'contacts': None, 'countr...",None,RECRUITING
1,NCT05380401,Metabolic Mechanisms Induced by Enteral Docosa...,2023-03-09,2022-05-18,2027-04,The University of Texas Health Science Center ...,OTHER,[Premature],INTERVENTIONAL,[NA],328.0,[{'armGroupLabels': ['DHA/ARA initially then n...,"[{'city': 'Los Angeles', 'contacts': [{'email'...","[{'class': 'NIH', 'name': 'Eunice Kennedy Shri...",RECRUITING
2,NCT05698901,Biomarkers and Cardiac Imaging Diagnostic Assa...,2023-09-19,2023-01-26,2026-09-30,Mackay Memorial Hospital,OTHER,[Fabry Disease],OBSERVATIONAL,None,150.0,"[{'armGroupLabels': ['Group B'], 'description'...","[{'city': 'Taipei', 'contacts': [{'email': 'ji...",None,RECRUITING
3,NCT00794001,Feedback Intervention and Treatment Times in S...,2007-10,2008-11-19,2025-12,Karl Heinrich Scholz,OTHER,[Myocardial Infarction],INTERVENTIONAL,[NA],50000.0,"[{'armGroupLabels': ['Data Feedback'], 'descri...","[{'city': 'Hildesheim', 'contacts': [{'email':...","[{'class': 'UNKNOWN', 'name': 'ALKK: Arbeitsge...",RECRUITING
4,NCT05754281,The PRECISION II Study: Evaluating the Accurac...,2023-02-03,2023-03-03,2026-09-30,Joslin Diabetes Center,OTHER,"[Type 1 Diabetes Mellitus, Type 2 Diabetes Mel...",OBSERVATIONAL,None,60.0,"[{'armGroupLabels': ['Study Cohort'], 'descrip...","[{'city': 'Boston', 'contacts': [{'email': 'jj...","[{'class': 'INDUSTRY', 'name': 'Cambridge Medi...",RECRUITING
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93232,NCT07452120,Comparison of the Effects of Deep Iliacus Plan...,2026-04-01,2026-03-05,2026-10-01,Sivas Numune Hospital,OTHER_GOV,"[Hip Arthroplasty, Postoperative Pain, Regiona...",INTERVENTIONAL,[NA],70.0,[{'armGroupLabels': ['Suprainguinal Fascia Ili...,"[{'city': 'Sivas', 'contacts': [{'email': 'fat...",None,NOT_YET_RECRUITING
93233,NCT07389720,Characterization of (A)Typical Sensorimotor Pa...,2024-05-21,2026-02-05,2026-12,IRCCS Eugenio Medea,OTHER,[Autism Spectrum Disorder],INTERVENTIONAL,[NA],300.0,"[{'armGroupLabels': ['Experimental: Clinical, ...","[{'city': 'Bosisio Parini', 'contacts': [{'ema...",None,RECRUITING
93234,NCT05779124,Soluble B-Cell Activating Factor and a Prolife...,2023-05-01,2023-03-22,2026-05-01,"First Affiliated Hospital, Sun Yat-Sen University",OTHER,"[Kidney Transplantation, Kidney Transplant Rej...",OBSERVATIONAL,None,176.0,None,"[{'city': 'Guangzhou', 'contacts': [{'email': ...","[{'class': 'OTHER', 'name': 'Fifth Affiliated ...",NOT_YET_RECRUITING
93235,NCT07348523,Comparison of the Effectiveness of Classical a...,2025-12-02,2026-01-16,2026-08-30,Samsun University,OTHER,"[Acute Pain, Spinal Stenosis Lumbar]",INTERVENTIONAL,[NA],60.0,[{'armGroupLabels': ['Active Comparator: Group...,"[{'city': 'Samsun', 'contacts': [{'email': 'ck...",None,RECRUITING
93236,NCT07473323,"A Phase 1 Randomized, Double-blind, Dose-Escal...",2026-05,2026-03-16,2027-05,Mediar Therapeutics,INDUSTRY,"[Healthy Adult Participants, Diabetic Kidney D...",INTERVENTIONAL,[PHASE1],88.0,"[{'armGroupLabels': ['MTX-439'], 'description'...",None,None,NOT_YET_RECRUITING

In [8]:
col = 'Intervention/Intervention Type'

def parse_cell(x):

    if isinstance(x, str):
        x = ast.literal_eval(x)

    if isinstance(x, (list, np.ndarray)) and len(x) > 0:
        item = x[0]

        return {
            k: v.tolist() if isinstance(v, np.ndarray) else v
            for k, v in item.items()
        }
    return None

intervention_df = pd.json_normalize(
    df_final[col].apply(parse_cell)
).add_prefix('Intervention_')

df_estudos = pd.concat([df_final.reset_index(drop=True), intervention_df.reset_index(drop=True)], axis=1)

df_estudos

,NCT Number,Study Title,Start Date,First Posted,Completion Date,Sponsor,Funder Type,Conditions,Study Type,Phases,Enrollment,Intervention/Intervention Type,Country,Collaborators,Study Status,Intervention_armGroupLabels,Intervention_description,Intervention_name,Intervention_otherNames,Intervention_type
0,NCT05659901,Integrated Prospective and Retrospective Obser...,2022-10-03,2022-12-21,2029-03,"Ionis Pharmaceuticals, Inc.",INDUSTRY,[Pelizaeus-Merzbacher Disease],OBSERVATIONAL,None,32.0,None,"[{'city': 'Atlanta', 'contacts': None, 'countr...",None,RECRUITING,NaN,NaN,NaN,NaN,NaN
1,NCT05380401,Metabolic Mechanisms Induced by Enteral Docosa...,2023-03-09,2022-05-18,2027-04,The University of Texas Health Science Center ...,OTHER,[Premature],INTERVENTIONAL,[NA],328.0,[{'armGroupLabels': ['DHA/ARA initially then n...,"[{'city': 'Los Angeles', 'contacts': [{'email'...","[{'class': 'NIH', 'name': 'Eunice Kennedy Shri...",RECRUITING,"[DHA/ARA initially then no supplement, DHA/ARA...",Dosage: 60 mg/kg/day of DHA and 120 mg/kg/day ...,Enfamil® DHA & ARA Supplement for Special Diet...,[DHA/ARA Supplement],DIETARY_SUPPLEMENT
2,NCT05698901,Biomarkers and Cardiac Imaging Diagnostic Assa...,2023-09-19,2023-01-26,2026-09-30,Mackay Memorial Hospital,OTHER,[Fabry Disease],OBSERVATIONAL,None,150.0,"[{'armGroupLabels': ['Group B'], 'description'...","[{'city': 'Taipei', 'contacts': [{'email': 'ji...",None,RECRUITING,[Group B],The treatment is following local reimbursement...,Agalsidase beta,None,DRUG
3,NCT00794001,Feedback Intervention and Treatment Times in S...,2007-10,2008-11-19,2025-12,Karl Heinrich Scholz,OTHER,[Myocardial Infarction],INTERVENTIONAL,[NA],50000.0,"[{'armGroupLabels': ['Data Feedback'], 'descri...","[{'city': 'Hildesheim', 'contacts': [{'email':...","[{'class': 'UNKNOWN', 'name': 'ALKK: Arbeitsge...",RECRUITING,[Data Feedback],Data analysis feedback: quarterly meetings wit...,Data analysis and Feedback,None,BEHAVIORAL
4,NCT05754281,The PRECISION II Study: Evaluating the Accurac...,2023-02-03,2023-03-03,2026-09-30,Joslin Diabetes Center,OTHER,"[Type 1 Diabetes Mellitus, Type 2 Diabetes Mel...",OBSERVATIONAL,None,60.0,"[{'armGroupLabels': ['Study Cohort'], 'descrip...","[{'city': 'Boston', 'contacts': [{'email': 'jj...","[{'class': 'INDUSTRY', 'name': 'Cambridge Medi...",RECRUITING,[Study Cohort],I. The 2nd Gen LabPatch chip which lies in the...,2nd Gen LabPatch Glucose Sensing System,None,DEVICE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93232,NCT07452120,Comparison of the Effects of Deep Iliacus Plan...,2026-04-01,2026-03-05,2026-10-01,Sivas Numune Hospital,OTHER_GOV,"[Hip Arthroplasty, Postoperative Pain, Regiona...",INTERVENTIONAL,[NA],70.0,[{'armGroupLabels': ['Suprainguinal Fascia Ili...,"[{'city': 'Sivas', 'contacts': [{'email': 'fat...",None,NOT_YET_RECRUITING,[Suprainguinal Fascia Iliaca Block (SIFIB)],Ultrasound-guided suprainguinal fascia iliaca ...,Suprainguinal Fascia Iliaca Block,None,PROCEDURE
93233,NCT07389720,Characterization of (A)Typical Sensorimotor Pa...,2024-05-21,2026-02-05,2026-12,IRCCS Eugenio Medea,OTHER,[Autism Spectrum Disorder],INTERVENTIONAL,[NA],300.0,"[{'armGroupLabels': ['Experimental: Clinical, ...","[{'city': 'Bosisio Parini', 'contacts': [{'ema...",None,RECRUITING,"[Experimental: Clinical, neuropsychological, n...",Clinical evaluation of participants by means o...,clinical assessment,None,DIAGNOSTIC_TEST
93234,NCT05779124,Soluble B-Cell Activating Factor and a Prolife...,2023-05-01,2023-03-22,2026-05-01,"First Affiliated Hospital, Sun Yat-Sen University",OTHER,"[Kidney Transplantation, Kidney Transplant Rej...",OBSERVATIONAL,None,176.0,None,"[{'city': 'Guangzhou', 'contacts': [{'email': ...","[{'class': 'OTHER', 'name': 'Fifth Affiliated ...",NOT_YET_RECRUITING,NaN,NaN,NaN,NaN,NaN
93235,NCT07348523,Comparison of the Effectiveness of Classical a...,2025-12-02,2026-01-16,2026-08-30,Samsun University,OTHER,"[Acute Pain, Spinal Stenosis Lumbar]",INTERVENTIONAL,[NA],60.0,[{'armGroupLabels': ['Active Comparator: Group...,"[{'city': 'Samsun', 'contacts': [{'email': 'ck...",None,RECRUITING,[Active Comparator: Group K-ESP],The erector spinae plane block will be perform...,The Classical Erector Spinae Plane Block,None,OTHER
93236,NCT07473323,"A Phase 1 Randomized, Double-blind, Dose-Escal...",2026-05,2026-03-16,2027-05,Mediar Therapeutics,INDUSTRY,"[Healthy Adult Participants, Diabetic Kidney D...",INTERVENTIONAL,[PHASE1],88.0,"[{'armGroupLabels': ['MTX-439'], 'description'...",None,None,NOT_YET_RECRUITING,[MTX-439],MTX-439 is a recombinant human immunoglobulin ...,MTX-439,None,BIOLOGICAL

In [9]:
df_final['Conditions'] = df_final['Conditions'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)
df_final['Conditions'] = df_final['Conditions'].str.join(', ')

In [10]:
df_final['Phases'] = df_final['Phases'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)
df_final['Phases'] = df_final['Phases'].str.join(', ')

In [11]:
df_final

,NCT Number,Study Title,Start Date,First Posted,Completion Date,Sponsor,Funder Type,Conditions,Study Type,Phases,Enrollment,Intervention/Intervention Type,Country,Collaborators,Study Status
0,NCT05659901,Integrated Prospective and Retrospective Obser...,2022-10-03,2022-12-21,2029-03,"Ionis Pharmaceuticals, Inc.",INDUSTRY,Pelizaeus-Merzbacher Disease,OBSERVATIONAL,None,32.0,None,"[{'city': 'Atlanta', 'contacts': None, 'countr...",None,RECRUITING
1,NCT05380401,Metabolic Mechanisms Induced by Enteral Docosa...,2023-03-09,2022-05-18,2027-04,The University of Texas Health Science Center ...,OTHER,Premature,INTERVENTIONAL,NA,328.0,[{'armGroupLabels': ['DHA/ARA initially then n...,"[{'city': 'Los Angeles', 'contacts': [{'email'...","[{'class': 'NIH', 'name': 'Eunice Kennedy Shri...",RECRUITING
2,NCT05698901,Biomarkers and Cardiac Imaging Diagnostic Assa...,2023-09-19,2023-01-26,2026-09-30,Mackay Memorial Hospital,OTHER,Fabry Disease,OBSERVATIONAL,None,150.0,"[{'armGroupLabels': ['Group B'], 'description'...","[{'city': 'Taipei', 'contacts': [{'email': 'ji...",None,RECRUITING
3,NCT00794001,Feedback Intervention and Treatment Times in S...,2007-10,2008-11-19,2025-12,Karl Heinrich Scholz,OTHER,Myocardial Infarction,INTERVENTIONAL,NA,50000.0,"[{'armGroupLabels': ['Data Feedback'], 'descri...","[{'city': 'Hildesheim', 'contacts': [{'email':...","[{'class': 'UNKNOWN', 'name': 'ALKK: Arbeitsge...",RECRUITING
4,NCT05754281,The PRECISION II Study: Evaluating the Accurac...,2023-02-03,2023-03-03,2026-09-30,Joslin Diabetes Center,OTHER,"Type 1 Diabetes Mellitus, Type 2 Diabetes Mell...",OBSERVATIONAL,None,60.0,"[{'armGroupLabels': ['Study Cohort'], 'descrip...","[{'city': 'Boston', 'contacts': [{'email': 'jj...","[{'class': 'INDUSTRY', 'name': 'Cambridge Medi...",RECRUITING
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93232,NCT07452120,Comparison of the Effects of Deep Iliacus Plan...,2026-04-01,2026-03-05,2026-10-01,Sivas Numune Hospital,OTHER_GOV,"Hip Arthroplasty, Postoperative Pain, Regional...",INTERVENTIONAL,NA,70.0,[{'armGroupLabels': ['Suprainguinal Fascia Ili...,"[{'city': 'Sivas', 'contacts': [{'email': 'fat...",None,NOT_YET_RECRUITING
93233,NCT07389720,Characterization of (A)Typical Sensorimotor Pa...,2024-05-21,2026-02-05,2026-12,IRCCS Eugenio Medea,OTHER,Autism Spectrum Disorder,INTERVENTIONAL,NA,300.0,"[{'armGroupLabels': ['Experimental: Clinical, ...","[{'city': 'Bosisio Parini', 'contacts': [{'ema...",None,RECRUITING
93234,NCT05779124,Soluble B-Cell Activating Factor and a Prolife...,2023-05-01,2023-03-22,2026-05-01,"First Affiliated Hospital, Sun Yat-Sen University",OTHER,"Kidney Transplantation, Kidney Transplant Reje...",OBSERVATIONAL,None,176.0,None,"[{'city': 'Guangzhou', 'contacts': [{'email': ...","[{'class': 'OTHER', 'name': 'Fifth Affiliated ...",NOT_YET_RECRUITING
93235,NCT07348523,Comparison of the Effectiveness of Classical a...,2025-12-02,2026-01-16,2026-08-30,Samsun University,OTHER,"Acute Pain, Spinal Stenosis Lumbar",INTERVENTIONAL,NA,60.0,[{'armGroupLabels': ['Active Comparator: Group...,"[{'city': 'Samsun', 'contacts': [{'email': 'ck...",None,RECRUITING
93236,NCT07473323,"A Phase 1 Randomized, Double-blind, Dose-Escal...",2026-05,2026-03-16,2027-05,Mediar Therapeutics,INDUSTRY,"Healthy Adult Participants, Diabetic Kidney Di...",INTERVENTIONAL,PHASE1,88.0,"[{'armGroupLabels': ['MTX-439'], 'description'...",None,None,NOT_YET_RECRUITING

In [10]:
n_estudos = df_estudos['NCT Number'].nunique()
n_estudos

92923

In [12]:
estudos_fase = (
    df_estudos[['NCT Number','Phases']]
    .astype({'Phases': 'string'})
    .drop_duplicates()
    .value_counts('Phases')
    .reset_index(name='n_estudos')
)
estudos_fase

                Phases  n_estudos
0               ['NA']      40284
1           ['PHASE2']       9590
2           ['PHASE1']       4962
3           ['PHASE3']       4627
4           ['PHASE4']       3434
5  ['PHASE1' 'PHASE2']       3151
6     ['EARLY_PHASE1']       1481
7  ['PHASE2' 'PHASE3']        970